datosgobar/series-tiempo-ar-api

series_tiempo_ar_api/apps/api/common/__init__.py, series_tiempo_ar_api/apps/api/common/constants.py, series_tiempo_ar_api/apps/api/common/operations.py, series_tiempo_ar_api/apps/api/indexing/constants.py, series_tiempo_ar_api/apps/api/indexing/indexer.py, series_tiempo_ar_api/apps/api/query/constants.py, series_tiempo_ar_api/apps/api/query/es_query.py
- Extrae las funciones de cálculos de las transformaciones de los datos (`change`, `percent_change`, ...) usados en la indexación a un módulo `common`
- Usa esas funciones para aplicar las transformaciones *despúes* de traer los datos cuando se hace una llamada a la API que pida datos con el intervalo de tiempo colapsado.
=> 67 collapse fix

series_tiempo_ar_api/apps/api/query/pipeline.py, series_tiempo_ar_api/apps/api/query/query.py, series_tiempo_ar_api/apps/api/tests/pipeline_tests.py
Closes #65 
Anteriormente se validaba el parámetro collapse_aggregation sólo si existía un collapse, ahora se hace de manera independiente. Esto corrige situaciones de colapso automático cuando se piden múltiples series de tiempo.
=> Valido y uso el parámetro collapse_aggregation por separado de collapse

series_tiempo_ar_api/apps/api/helpers.py, series_tiempo_ar_api/apps/api/query/constants.py, series_tiempo_ar_api/apps/api/query/es_query.py, series_tiempo_ar_api/apps/api/tests/helpers.py, series_tiempo_ar_api/apps/api/tests/query_tests.py
- Permite pasar `collapse=week` a la API para obtener agregaciones semanales de las series
- Pequeño fix relacionado con #63 cuando se calculan los valores en el collapse de varias series
=> 60 week collapse

series_tiempo_ar_api/apps/api/tests/view_tests.py, series_tiempo_ar_api/apps/api/urls.py, series_tiempo_ar_api/apps/api/views.py
Closes #86 
Al llegar un request, se itera sobre los parámetros del mismo y se llevan todos los valores a lowercase, 
*excepto* el de `ids`. Así la API se comporta de manera igual, independiente del *case* de cada parámetro.
=> 86 ignore case

conf/settings/api.py, series_tiempo_ar_api/apps/api/query/pipeline.py, series_tiempo_ar_api/apps/api/query/strings.py, series_tiempo_ar_api/apps/api/tests/pipeline_tests/ids_tests.py
Closes #102 
Si llega un query con una cantidad por encima de ese límite (establecido en 20), se rechaza la operación y devuelve un error
=> Agrego un límite para la cantidad de series a pedir posibles

series_tiempo_ar_api/apps/api/query/constants.py, series_tiempo_ar_api/apps/api/query/es_query/collapse_query.py, series_tiempo_ar_api/apps/api/tests/collapse_query_tests.py
Closes #111 
Aplica primero la transformación end_of_period sobre el valor original de la serie, y *luego* la transformación pedida (change, pct_change, ...)
=> Bugfix a transformación concatenada con end of period

conf/settings/api.py, conf/settings/base.py, conf/settings/production.py, conf/settings/staging.py, requirements/base.txt, series_tiempo_ar_api/apps/management/migrations/read_datajson_group.py, series_tiempo_ar_api/apps/management/models.py, series_tiempo_ar_api/apps/management/tests/tasks_tests.py, series_tiempo_ar_api/urls.py
Agrega [`des`](https://github.com/jamiecounsell/django-des) a la aplicación, permite configurar el servidor SMTP usado desde el django admin.
Cambia la lógica de la generación del reporte para solo mandar mails a los usuarios dentro de un grupo `read_datajson_recipients` en vez de los usuarios taggeados como "staff".
=> 158 smtp config

series_tiempo_ar_api/apps/management/models.py, series_tiempo_ar_api/libs/indexing/catalog_reader.py, series_tiempo_ar_api/libs/indexing/database_loader.py, series_tiempo_ar_api/libs/indexing/report/indicators.py, series_tiempo_ar_api/libs/indexing/report/report_generator.py, series_tiempo_ar_api/libs/indexing/tasks.py, series_tiempo_ar_api/libs/indexing/tests/loader_tests.py, series_tiempo_ar_api/libs/indexing/tests/reader_tests.py
Closes #207 
Modifica el comportamiento del cálculo de indicadores:
- Los valores de series no actualizadas se calcula sobre la cantidad de series indexables en vez de las totales
- Se guardan los indicadores en la instancia de Redis, y luego se persisten en la base de datos relacional
=> Indicadores de serie 2

series_tiempo_ar_api/apps/metadata/management/commands/index_metadata.py
Modifica `index_metadata` para leer múltiples URLs, o si ninguna es especificada, leer las URLs desde los modelos Node de la base de datos. Necesario para facilitar la automatización de correr este comando periódicamente
=> Indexación automática de metadatos

series_tiempo_ar_api/apps/analytics/templates/admin/analytics/change_list.html, series_tiempo_ar_api/apps/analytics/tests/view_tests.py, series_tiempo_ar_api/apps/analytics/urls.py, series_tiempo_ar_api/apps/analytics/views.py
Closes #231 
El endpoint de descarga de analytics (`/analytics/analytics.csv`) ahora pasa a generar el .csv de manera sincrónica. Este comportamiento es temporal hasta migrar los analytics fuera del proyecto, porque esta generación no escala.
=> Exporto analytics de manera sincrónica

series_tiempo_ar_api/apps/api/query/response.py, series_tiempo_ar_api/apps/api/tests/response_tests.py
Este fenómeno solo ocurre cuando se setea el caracter decimal de los valores a algo no default.
Antes: se casteaba el None a `str` y se mostraba en la respuesta CSV
2015-04-01,"0,066"
2015-07-01,"0,059"
2015-10-01,None
2016-01-01,None
2016-04-01,"0,093"
2016-07-01,"0,085"
Ahora: se chequea por None y no se castea si el valor es nulo
2015-04-01,"0,066"
2015-07-01,"0,059"
2015-10-01,
2016-01-01,
2016-04-01,"0,093"
2016-07-01,"0,085"
=> Borro los none de la respuesta CSV

series_tiempo_ar_api/apps/api/query/constants.py, series_tiempo_ar_api/apps/api/query/es_query/es_query.py, series_tiempo_ar_api/apps/api/query/es_query/response_formatter.py, series_tiempo_ar_api/apps/api/query/es_query/series.py, series_tiempo_ar_api/apps/api/query/query.py, series_tiempo_ar_api/apps/api/tests/es_query_tests.py
Closes #236
- Muevo código que formatea la respuesta recibida de ES a un módulo aparte
- Modifico dicho código para que pueda leer resultados desde aggregations de ES en ciertos casos
- Implemento max y min usando aggregations de ES
=> 236 add max min aggs

series_tiempo_ar_api/apps/analytics/tasks.py, series_tiempo_ar_api/apps/analytics/tests/export_tests.py
Closes #212 
Se les aplica `localtime` de utils de django antes de ser escritas al CSV.
Además se cambia un poco la lógica de la escritura del CSV para poder aplicarle funciones a cada campo a exportar
=> Corrijo timezone de fechas exportadas en analytics

series_tiempo_ar_api/apps/metadata/constants.py, series_tiempo_ar_api/apps/metadata/indexer/doc_types.py, series_tiempo_ar_api/apps/metadata/indexer/metadata_indexer.py, series_tiempo_ar_api/apps/metadata/queries/query.py, series_tiempo_ar_api/apps/metadata/tests/tests.py, series_tiempo_ar_api/apps/metadata/urls.py, series_tiempo_ar_api/apps/metadata/views.py
Closes #177 
Agrega los parámetros indicados en #177 para hacer filtros OR y AND por los fields de cada documento de metadatos cargado
=> 177 enhance search

series_tiempo_ar_api/apps/analytics/tasks.py
Closes #301 
Los errores eran de **export**, no de import! Los timeouts ocurrían porque escribir un CSV de 5 millones de rows tarda más que 180 segundos. Queda pendiente resolver el problema de fondo de estar escribiendo un CSV de 5 millones de rows.
=> Aumento el timeout de export_analytics

series_tiempo_ar_api/apps/metadata/constants.py, series_tiempo_ar_api/apps/metadata/indexer/doc_types.py, series_tiempo_ar_api/apps/metadata/indexer/index.py, series_tiempo_ar_api/apps/metadata/indexer/metadata_indexer.py, series_tiempo_ar_api/apps/metadata/queries/query.py, series_tiempo_ar_api/apps/metadata/tests/indexer_tests.py
Se configura un analyzer para el índice, y se aplica en todos los campos relevantes a una búsqueda.
Se copian todos los campos a uno nuevo, 'all', para reemplazar el uso de _all, deprecado en ES 6.0
En la view de query, se hace la búsqueda por 'all' en vez del deprecado '_all'.
Closes #331
=> Reorganizo el índice de metadatos

conf/settings/api/api.py, series_tiempo_ar_api/apps/api/tests/view_tests.py, series_tiempo_ar_api/apps/dump/tests/view_tests.py, series_tiempo_ar_api/libs/indexing/indexer/distribution_indexer.py, series_tiempo_ar_api/libs/indexing/indexer/index.py
El default es 10000, si se pedía un valor mayor a ese se devolvía un error 500. Se aumenta a 100000. Sabiendo que la gran mayoría de las series actuales (>99.9%) tienen menos de 10000 valores, no debería afectar negativamente la performance de la aplicación.
Además aprovecho para pasar a utilizar `elasticsearch_dsl` para manejar el índice de series de tiempo.
Closes #326
=> Aumento el límite de window de ES

series_tiempo_ar_api/apps/api/query/es_query/series.py, series_tiempo_ar_api/apps/api/query/pipeline.py
Closes #354 
Este cambio permite que en otro lado cuando acotamos la cantidad de respuestas por response = response[:limit] ese `limit` sea el pasado por parámetro y no la suma que valía anteriormente
=> Fix a tamaño de respuesta mayor al pedido

series_tiempo_ar_api/libs/indexing/indexer/distribution_indexer.py, series_tiempo_ar_api/libs/indexing/indexer/utils.py, series_tiempo_ar_api/libs/indexing/tests/utils_tests.py
django_datajsonar no contempla uniqueness de las series de tiempo, y
crea un modelo nuevo si un Field cambia de titulo. Antes
de indexar datos corremos un pequeño filtro que se encargue de borrar
series duplicadas.
Closes #392
=> Borro series duplicadas antes de indexar

series_tiempo_ar_api/apps/dump/generator/xlsx/generator.py, series_tiempo_ar_api/apps/dump/generator/xlsx/workbook.py, series_tiempo_ar_api/apps/dump/tests/xlsx_generator_tests.py
Se ordenan ahora primero por su frecuencia, y luego por su número de
página. Así anual-1 va a venir antes de diaria-1 y diaria-2
=> Modifico el orden de las hojas de dumps XLSX

conf/settings/api/api.py, series_tiempo_ar_api/apps/api/helpers.py, series_tiempo_ar_api/apps/api/query/constants.py, series_tiempo_ar_api/apps/api/query/es_query/es_query.py, series_tiempo_ar_api/apps/api/query/pipeline.py, series_tiempo_ar_api/apps/api/query/query.py, series_tiempo_ar_api/apps/api/query/strings.py, series_tiempo_ar_api/apps/api/tests/pipeline_tests/last_tests.py
last=X (número positivo, hasta 1000 por defecto), devuelve los últimos X
resultados de la serie pedida, en orden de fechas ascendiente.
=> Endpoint series: Parámetro 'last'

series_tiempo_ar_api/apps/dump/models.py, series_tiempo_ar_api/apps/dump/tests/csv_generator_tests.py, series_tiempo_ar_api/apps/dump/tests/model_tests.py, series_tiempo_ar_api/libs/indexing/tests/attachment_tests.py, series_tiempo_ar_api/libs/indexing/tests/metadata_tests.py
Antes: el script de generación de dumps XLSX global agarraba "los últimos dumps csv generados, filtrando por `node=None`" como base. El filtro ese no se estaba aplicando, y devolvía dumps asociados a cualquier nodo, no a ninguno, haciendo que los que realmente buscabamos con `node=None` nunca se procesen.
=> Fix a los dumps globales no generándose

series_tiempo_ar_api/apps/metadata/constants.py, series_tiempo_ar_api/apps/metadata/indexer/catalog_meta_indexer.py, series_tiempo_ar_api/apps/metadata/indexer/doc_types.py, series_tiempo_ar_api/apps/metadata/indexer/index.py, series_tiempo_ar_api/apps/metadata/indexer/metadata_indexer.py, series_tiempo_ar_api/apps/metadata/queries/query.py, series_tiempo_ar_api/apps/metadata/queries/query_terms.py, series_tiempo_ar_api/apps/metadata/tests/index_tests.py, series_tiempo_ar_api/apps/metadata/tests/indexer_tests.py, series_tiempo_ar_api/apps/metadata/utils.py
Se pasa de un índice (de Elasticsearch) único de metadatos a generar un índice por corrida de la rutina de indexación de metadatos, y rotar un alias que apunta siempre al índice más reciente. Tiene la intención de solucionar la inconsistencia en la búsqueda de series y los resultados de datos: actualmente aparecen series de tiempo en los resultados de búsquedas que no están indexadas correctamente. Al generarse un índice nuevo en cada corrida, los resultados siempre devolverán series que estamos seguros que existen al momento de la corrida.
=> Restructuración del índice de metadatos

series_tiempo_ar_api/apps/api/tests/pipeline_tests/pagination_tests.py, series_tiempo_ar_api/apps/dump/generator/dump_csv_writer.py, series_tiempo_ar_api/apps/dump/generator/generator.py, series_tiempo_ar_api/apps/dump/generator/metadata.py, series_tiempo_ar_api/apps/dump/generator/sources.py
Hace una única lectura grande a la base de datos para metadatos
enriquecidos como paso previo, y maneja el resto en memoria.
Antes se hacía 1 lectura a la base de datos por cada valor de metadato
enriquecido a leer, varios de ellos se leían (mucho) más de una vez. Al
leerlos todos de una en el método init_data() se logra una mejora
considerable de performance (~30m en 1 core vs varias horas en
paralelo), solo teniendo una penalidad de memoria de algunos cientos de
mb, el proceso entero en su totalidad consume 400-500mb, rango manejable
por los servidores.
=> Optimizacion de DB en dumps CSV

series_tiempo_ar_api/apps/api/query/es_query/es_query.py, series_tiempo_ar_api/apps/api/query/es_query/periods_between.py, series_tiempo_ar_api/apps/api/query/es_query/series.py, series_tiempo_ar_api/apps/api/query/query.py, series_tiempo_ar_api/apps/api/tests/pipeline_tests/ids_tests.py, series_tiempo_ar_api/apps/api/tests/series_tests.py
El bug en cuestión era aplicar el parámetro start pasado por la query
del usuario directamente a cada serie, sin tener en cuenta la diferencia
entre los índices de tiempo entre ellas. Si una serie comienza mucho
después que otra, no se le debe aplicar un start (desfasaje) igual a la
serie con menor índice, sino la diferencia entre el parámetro start y
los períodos entre ella y la serie de menor índice. Este fix soluciona
problemas de "serie no encontrada" en el front end de la API cuando se
piden varias series de tiempo a la vez, una con un índice mucho menor a
las demás.
=> Bugfix: series sin valores cuando se piden de a más de una

requirements/base.txt, series_tiempo_ar_api/libs/indexing/indexer/distribution_indexer.py, series_tiempo_ar_api/libs/indexing/tests/scraper_tests.py
A partir de la versión 0.2.0 de la librería series-tiempo-ar, pueden
llegar a existir series de tiempo sin ningún valor. Agrego un chequeo en
el indexador de distribuciones para desestimar estas series.
=>  No indexo series sin valores

requirements/testing.txt, series_tiempo_ar_api/apps/management/meta_keys.py, series_tiempo_ar_api/libs/indexing/indexer/metadata.py, series_tiempo_ar_api/libs/indexing/tests/metadata_tests.py
Se generan cada vez que se actualiza una distribución.
Se muestran de manera automática en la respuesta del endpoint /series, cuando se pide `metadata=full` o `metadata=only`.
=> Agrego metadatos enriquecidos: max, min, average

series_tiempo_ar_api/apps/api/query/metadata_response.py, series_tiempo_ar_api/apps/api/query/query.py, series_tiempo_ar_api/apps/api/tests/metadata_tests.py
Mejor encapsulamiento del código generador de la respuesta de metadatos
Ahora MetadataResponse tiene un único método "público", `get_response`, que devuelve los metadatos de la serie según los criterios pasados como variables de instancia, de `simple`, y `flat` (booleanos)
=> Refactor de legibilidad en MetadataResponse

series_tiempo_ar_api/apps/api/query/constants.py, series_tiempo_ar_api/apps/api/query/query.py, series_tiempo_ar_api/apps/api/tests/query_tests.py
Agrega a los metadatos de series ('field') los campos
'representation_mode' y 'representation_mode_units'. El primer campo
tendrá como valor la copia exacta del parámetro modo de representación
pedido para la serie. El segundo, tendrá un nombre _verbose_ del modo
de representación.
=> Modos de representación como metadatos

series_tiempo_ar_api/apps/analytics/elasticsearch/constants.py, series_tiempo_ar_api/apps/analytics/elasticsearch/doc.py, series_tiempo_ar_api/apps/analytics/elasticsearch/index.py, series_tiempo_ar_api/apps/analytics/importer.py, series_tiempo_ar_api/apps/analytics/management/commands/index_to_es.py, series_tiempo_ar_api/apps/analytics/tasks.py, series_tiempo_ar_api/apps/analytics/tests/es_tests.py, series_tiempo_ar_api/apps/analytics/tests/import_tests.py
Mete toda la lógica de indexación en una clase `AnalyticsIndexer`, que utiliza un documento de `elasticsearch-dsl` para indexar un queryset / iterable compuesto de modelos `Query` a Elasticsearch.
Pasa a usar esta nueva clase durante la rutina de importado de analytics, además de cargar las queries en la DB, las carga en Elasticsearch.
Agrega un nuevo management command para correr sólo la rutina de indexación a ES a partir de **todos** los modelos Query en la DB cargados, a modo de sincronización de datos.
=> Indexo queries a Elasticsearch

series_tiempo_ar_api/apps/management/meta_keys.py, series_tiempo_ar_api/libs/indexing/popularity.py, series_tiempo_ar_api/libs/indexing/tasks.py, series_tiempo_ar_api/libs/indexing/tests/popularity_metadata_tests.py
Utiliza el índice de queries de Elasticsearch generado previamente para calcular la cantidad de consultas a todas las series en distintos intervalos de tiempo:
- Últimos 30 días
- Últimos 90 días
- Últimos 180 días
- Histórico completo
Estos metadatos se calculan para *todas* las series, *todos* los días, se estén actualizando o no las distribuciones
=> Metadatos de popularidad de las series

series_tiempo_ar_api/apps/api/query/pipeline.py, series_tiempo_ar_api/apps/api/query/query.py, series_tiempo_ar_api/apps/api/tests/pipeline_tests/sort_tests.py, series_tiempo_ar_api/apps/api/tests/query_tests.py
Refactor al método de agregado de series para que siempre se actualicen todas las frecuencias de todas las series a la de mayor frecuencia. Por ejemplo, si se piden 3 series, una anual y dos mensuales, en cada llamada al agregado de series se actualiza la frecuencia para que sea la mayor (anual), y asegurarse que no quede configurada una frecuencia mensual (sería inválido)
=> Corrijo agregado de series con distintas freqs

series_tiempo_ar_api/apps/api/query/pipeline.py, series_tiempo_ar_api/apps/api/tests/helpers.py, series_tiempo_ar_api/apps/api/tests/pipeline_tests/ids_tests.py, series_tiempo_ar_api/apps/management/meta_keys.py
Un metadato en particular, INDEX_START, se volvió esencial para el
funcionamiento correcto de la API frente a pedidos de varias series de
tiempo. Se agrega un chequeo de existencia sobre cada serie pedida, para
evitar errores en el armado de la respuesta si el metadato no es
encontrado
Closes #471
=> Valido la existencia de metadatos de series

series_tiempo_ar_api/apps/api/query/metadata_response.py, series_tiempo_ar_api/apps/api/tests/metadata_tests.py, series_tiempo_ar_api/apps/metadata/admin.py
El hecho que una serie es porcentual o no se decide a través del panel de administración, donde se pueden marcar manualmente a las unidades de series como porcentuales o no (por default no lo son)
Closes #479
=> Muestro si una serie es porcentual en la respuesta

series_tiempo_ar_api/apps/metadata/queries/query_terms.py, series_tiempo_ar_api/apps/metadata/tests/field_term_tests.py, series_tiempo_ar_api/apps/metadata/tests/view_tests.py
Simplemente muestro el resultado de `doc_count` que ya se estaba calculando previamente. 
Closes #476, closes #477
=> Muestro cantidad de hits en endpoints auxiliares

series_tiempo_ar_api/libs/field_utils.py, series_tiempo_ar_api/libs/indexing/indexer/distribution_indexer.py, series_tiempo_ar_api/libs/indexing/tests/metadata_tests.py, series_tiempo_ar_api/libs/indexing/tests/reader_tests.py, series_tiempo_ar_api/libs/indexing/tests/samples/different_time_index_name.csv, series_tiempo_ar_api/libs/indexing/tests/samples/different_time_index_name.json
Antes se buscaba al índice de tiempo tomando la columna con título `INDEX_COLUMN`. Si no existía se lanzaba excepción.
Con este PR se pasa a buscar el título del índice de tiempo en los metadatos de la distribución, buscando sobre las series aquella que tenga `specialType == "time_index`. La ventaja de este cambio es poder indexar distribuciones con títulos arbitrarios, no tienen que valer `INDEX_COLUMN`.
=> Leo el índice de tiempo desde metadatos durante indexación

series_tiempo_ar_api/apps/metadata/indexer/catalog_meta_indexer.py, series_tiempo_ar_api/apps/metadata/tests/indexer_tests.py
Antes: Se indexaban las series que estén disponibles **y** no tengan error, **y** estén presentes. Ese comportamiento era erróneo, pues una serie con error que esté disponible puede seguir siendo consultada, idem con una serie ya no más presente. Se corrige ese comportamiento, indexando todas las series disponibles sin filtros adicionales, y se agregan pruebas de regresión.
=> Indexo las series si están disponibles

series_tiempo_ar_api/libs/indexing/popularity.py, series_tiempo_ar_api/libs/indexing/tests/popularity_metadata_tests.py
Antes se usaba update_or_create que traía un gran cuello de botella. Pasamos a actualizar los metadatos borrandolos todos y regenerandolos con bulk_create
=> Improve popularity metadata update

series_tiempo_ar_api/libs/indexing/report/report_generator.py, series_tiempo_ar_api/libs/indexing/tests/report_tests.py
Closes #532 
En vez de pasar self.task.logs (que ni siquiera tenía garantía de contener los errores de las distribuciones), ahora se leen individualmente por cada distribución, y si el reporte es para un nodo individual, se filtran los errores que no sean de ese nodo.
=> Filtro errores sólo para el catálogo actual

scripts/pycodestyle.sh, series_tiempo_ar_api/apps/api/query/constants.py, series_tiempo_ar_api/apps/api/query/query.py, series_tiempo_ar_api/apps/api/query/series_query.py, series_tiempo_ar_api/apps/api/tests/query_tests.py, series_tiempo_ar_api/apps/api/tests/series_query_tests.py
- Saca toda la lógica de armado de metadatos en `Query` en un objeto aparte, `SeriesQuery`, que lo arma por cada serie.
- Corrijo el bug de que si se agregaba dos series de mismo id pero con diferente rep mode, (ejemplo: http://localhost:8000/api/series/?ids=116.4_TCRZE_2015_D_26_49,116.4_TCRZE_2015_D_26_49:percent_change), el campo `representation_mode_units` decía `value` en ambos, cuando debía decir `value` para el primero y `percent_change` para el segundo
Closes #589
=> Bugfix de representation_mode_units + refactor

series_tiempo_ar_api/apps/api/query/metadata_response.py, series_tiempo_ar_api/apps/api/query/series_query.py, series_tiempo_ar_api/apps/api/tests/helpers.py, series_tiempo_ar_api/apps/api/tests/metadata_tests.py, series_tiempo_ar_api/apps/api/tests/query_tests.py, series_tiempo_ar_api/apps/api/tests/series_query_tests.py, series_tiempo_ar_api/apps/metadata/models.py, series_tiempo_ar_api/apps/metadata/tests/series_units_tests.py, series_tiempo_ar_api/apps/metadata/tests/update_units_tests.py
Closes #593 
Problema: La lógica `is_percentage` se hacía en dos módulos distintos, primero en `MetadataResponse` y luego en `SeriesQuery`. Este último pisaba el resultado del primero, haciendo que a veces se muestre `false` cuando debería ser `true`. Adicionalmente, `SeriesQuery` siempre mostraba el resultado de `is_percentage`, cuando en realidad solo debería aparecer ese campo si se pide metadatos "completos" (`simple=False`)
Solución: Merge de lógica todo en `SeriesQuery`. Agrego varios casos de prueba, unitarios y de integración.
=> is_percentage fix

templates/indexing/report.html
=> Reemplazo newlines por breaks en reporte HTML

series_tiempo_ar_api/apps/management/tasks/indexation.py, series_tiempo_ar_api/libs/indexing/tests/data_index_task_tests.py
Closes #621 
- Arreglo corridas de indexacion: al crear a mano y seleccionar un nodo ya no se indexan todos los nodos
=> Fix corridas de indexacion para un nodo

series_tiempo_ar_api/apps/api/query/es_query/series.py, series_tiempo_ar_api/apps/api/tests/endpoint_tests/aggregations_tests.py
La agregación de ES se realizaba sobre todos los valores indexados de las series,
incluso los valores de collapse precalculados. Se agrega un filtro adicional
según el período de la serie original para no considerar estos valores sobre
la agregación
Closes #653
=> Fix a aggs max/min

series_tiempo_ar_api/libs/datajsonar_repositories/distribution_repository.py, series_tiempo_ar_api/libs/datajsonar_repositories/tests/distribution_repository_tests.py
Closes #658 
Solución permanente al caso 'se cambió el ID del índice de tiempo y ahora existen múltiples series taggeadas como time_index, con una sola con present=True'
También saqué todos los mocks de los test cases, pasando a testear de una manera más de integración
=> Manejo casos de get time index cuando la distribución no esté presente
