datosgobar/series-tiempo-ar-api

series_tiempo_ar_api/apps/api/indexing/indexer.py

Fix a la indexación imprecisa de números decimales

---

conf/settings/base.py
series_tiempo_ar_api/apps/api/indexing/catalog_reader.py
series_tiempo_ar_api/apps/api/indexing/database_loader.py
series_tiempo_ar_api/apps/api/indexing/indexer.py
series_tiempo_ar_api/apps/api/indexing/scraping.py
series_tiempo_ar_api/apps/api/management/commands/read_datajson.py

Agrego un handler para el package de la aplicacion.
Asi la forma de agregar logs es consistente en toda la app.

Mejora en el logging

---

series_tiempo_ar_api/apps/api/query/pipeline.py
series_tiempo_ar_api/apps/api/tests/pipeline_tests/collapse_tests.py

Valido que el intervalo de colapso no sea semestral

---

series_tiempo_ar_api/apps/api/query/es_query/base_query.py
series_tiempo_ar_api/apps/api/tests/es_query_tests.py

Limito la cantidad de filas al límite de la query

---

series_tiempo_ar_api/urls.py

Agrego el prefijo 'api', asi el endpoint de series quedaria /api/series/

Agrego el prefijo 'api'

---

conf/settings/base.py
requirements/base.txt
series_tiempo_ar_api/apps/analytics/admin.py

Permite generar dumps de la base de datos de la tabla Query en varios formatos.
Los campos exportados son, en orden:
- timestamp
- ip_address
- ids
- params (JSON con todos los parámetros pedidos)

Agrego opcion para exportar las queries guardadas

---

conf/settings/api.py
series_tiempo_ar_api/apps/api/common/operations.py
series_tiempo_ar_api/apps/api/indexing/distribution_indexer.py
series_tiempo_ar_api/apps/api/indexing/indexer.py
series_tiempo_ar_api/apps/api/tasks.py
series_tiempo_ar_api/apps/api/tests/reader_tests.py
series_tiempo_ar_api/apps/management/management/commands/read_datajson.py
series_tiempo_ar_api/apps/management/tests/read_datajson_tests.py

142 indexing fixes

---

series_tiempo_ar_api/apps/api/indexing/scraping.py

Fix a pandas fallando en la lectura de URLs no ascii

---

series_tiempo_ar_api/apps/api/admin.py

179 admin panel filters

---

series_tiempo_ar_api/apps/analytics/analytics.py
series_tiempo_ar_api/apps/analytics/models.py
series_tiempo_ar_api/apps/analytics/tests.py
series_tiempo_ar_api/apps/analytics/utils.py
series_tiempo_ar_api/apps/analytics/views.py

Uso el timestamp de kong en vez de al momento de crear la query.

Timestamp de kong

---

series_tiempo_ar_api/apps/analytics/tests.py
series_tiempo_ar_api/apps/analytics/views.py

No loggeo entradas fuera de la API de series de tiempo

---

series_tiempo_ar_api/apps/analytics/tests.py
series_tiempo_ar_api/apps/analytics/views.py

Fix temporal, que funciona con las URLs actuales, hasta que movamos la lógica a api_gateway

No guardo accesos al panel de admin en analytics

---

series_tiempo_ar_api/apps/metadata/indexer/doc_types.py
series_tiempo_ar_api/apps/metadata/indexer/metadata_indexer.py
series_tiempo_ar_api/apps/metadata/tests/view_tests.py
series_tiempo_ar_api/apps/metadata/urls.py
series_tiempo_ar_api/apps/metadata/views.py

publisher name endpoint

---

series_tiempo_ar_api/libs/indexing/database_loader.py
series_tiempo_ar_api/libs/indexing/tests/loader_tests.py
series_tiempo_ar_api/libs/indexing/tests/samples/full_ts_data_changed_distribution.json

Permito que las series puedan cambiar distribuciones dentro de su catálogo

---

series_tiempo_ar_api/libs/indexing/report/report_generator.py

Closes #234 
También borra un par de variables que ya no son usadas

Muestro los valores del reporte como enteros 

---

series_tiempo_ar_api/apps/analytics/templates/admin/analytics/change_list.html
series_tiempo_ar_api/apps/analytics/tests/view_tests.py
series_tiempo_ar_api/apps/analytics/urls.py
series_tiempo_ar_api/apps/analytics/views.py

Reverts datosgobar/series-tiempo-ar-api#241

Revert "Exporto analytics de manera sincrónica"

---

series_tiempo_ar_api/libs/indexing/tasks.py

refs:#227
"fix" temporal para obtener más información sobre lo que está pasando en ambientes de desarrollo

Loggeo traceback en el caso de que no haya mensaje descriptivo

---

templates/indexing/report.html

Agrego una sección de resumen al reporte

---

series_tiempo_ar_api/apps/api/query/es_query/response_formatter.py
series_tiempo_ar_api/apps/api/tests/es_query_tests.py
series_tiempo_ar_api/apps/api/tests/pipeline_tests/ids_tests.py

Closes #287 
Filtro los valores null inicial del armado de respuesta de `/series`

287 initial nulls

---

series_tiempo_ar_api/apps/management/meta_keys.py
series_tiempo_ar_api/libs/indexing/indexer/distribution_indexer.py
series_tiempo_ar_api/libs/indexing/indexer/metadata.py
series_tiempo_ar_api/libs/indexing/tests/metadata_tests.py

Closes #294 
Agrega al proceso de indexación de datos el cálculo de varios _metadatos enriquecidos_ con indicadores de interés de cada serie indexada (ver el issue para el detalle de lo que se calcula).

Metadatos enriquecidos de las series

---

series_tiempo_ar_api/apps/api/query/query.py
series_tiempo_ar_api/apps/api/tests/helpers.py
series_tiempo_ar_api/apps/api/tests/query_tests.py

Muestro metadatos enriquecidos en respuesta de /series

---

series_tiempo_ar_api/apps/dump/tests/csv_generator_tests.py
series_tiempo_ar_api/apps/management/meta_keys.py
series_tiempo_ar_api/apps/metadata/migrations/enhanced_meta_name_change.py
series_tiempo_ar_api/apps/metadata/queries/query.py
series_tiempo_ar_api/apps/metadata/tests/query_tests.py
series_tiempo_ar_api/apps/metadata/tests/utils.py

Cambio de nombre de algunos metadatos enriquecidos

---

conf/settings/api/api.py

Aumento el máximo de series por request

---

series_tiempo_ar_api/apps/metadata/constants.py
series_tiempo_ar_api/apps/metadata/queries/query.py
series_tiempo_ar_api/apps/metadata/tests/query_tests.py
series_tiempo_ar_api/apps/metadata/tests/view_tests.py

Renombro el parámetro de offset

---

series_tiempo_ar_api/apps/api/query/es_query/es_query.py
series_tiempo_ar_api/apps/api/query/query.py
series_tiempo_ar_api/apps/api/query/strings.py
series_tiempo_ar_api/apps/api/tests/es_query_tests.py
series_tiempo_ar_api/apps/api/tests/query_tests.py

Agrego un parámetro count a la respuesta

---

series_tiempo_ar_api/libs/indexing/indexer/metadata.py
series_tiempo_ar_api/libs/indexing/tests/metadata_tests.py

Closes #341 
Va a ser necesario correr una indexación con --force

Guardo metadatos de inicio y fin de fechas como date()

---

series_tiempo_ar_api/apps/api/helpers.py
series_tiempo_ar_api/apps/api/query/es_query/es_query.py
series_tiempo_ar_api/apps/api/query/es_query/series.py
series_tiempo_ar_api/apps/api/tests/query_tests.py

Corrijo offsets inválidos cuando se aplica rep_mode

---

series_tiempo_ar_api/apps/api/query/metadata_response.py
series_tiempo_ar_api/apps/api/query/query.py
series_tiempo_ar_api/apps/api/tests/metadata_tests.py

Closes #312 
Respuesta actual: ```"theme": [
"internacional"
],```
Ahora:  ```
"theme": [
{
"label": "Economía Internacional",
"id": "internacional",
"description": "Series económicas mundiales"
}
],```

Reemplazo theme ids por objeto con más info

---

docs/reference/api_reference.md
docs/reference/search_reference.md
docs/swagger.yml
mkdocs.yml

Closes #353
Para probar: usar `mkdocs` de python para RTD, y `swagger-editor` para Swagger.

Documentación de /search/

---

series_tiempo_ar_api/apps/analytics/admin.py

Optimizo admin view de Query

---

series_tiempo_ar_api/libs/indexing/report/attachments.py

Display de mensaje de error en reportes

---

series_tiempo_ar_api/apps/metadata/admin.py
series_tiempo_ar_api/apps/metadata/tests/utils_tests.py
series_tiempo_ar_api/apps/metadata/utils.py

Borro metadatos del índice de ES al borrar fields de la db

---

series_tiempo_ar_api/apps/dump/admin.py
series_tiempo_ar_api/apps/dump/generator/dump_csv_writer.py
series_tiempo_ar_api/apps/dump/generator/xlsx/generator.py
series_tiempo_ar_api/apps/dump/generator/xlsx/workbook.py
series_tiempo_ar_api/apps/dump/generator/xlsx/worksheet.py
series_tiempo_ar_api/apps/dump/management/commands/generate_dump.py
series_tiempo_ar_api/apps/dump/management/commands/generate_xlsx_dump.py
series_tiempo_ar_api/apps/dump/models.py
series_tiempo_ar_api/apps/dump/tasks.py
series_tiempo_ar_api/utils.py

- Uso de `AbstractTaskAdmin` de django_datajsonar para el admin de los dumps
- Separo los valores de dumps XLSX en distintas hojas según su frecuencia: los valores de series anuales van a una hoja, las trimestrales a otra, etc
- Refactor de código para usar clases y objetos en vez de funciones sueltas.

Refactor xlsx dumps

---

series_tiempo_ar_api/libs/indexing/scraping.py
series_tiempo_ar_api/libs/indexing/strings.py
series_tiempo_ar_api/libs/indexing/tasks.py
series_tiempo_ar_api/libs/indexing/tests/scraper_tests.py

400 validate missing identifiers

---

series_tiempo_ar_api/apps/dump/models.py

Evito posibles condiciones de carrera al escribirse y borrar al mismo file name utilizando el ID del modelo del Dump original, que es único

EAsigno un nombre único a zipfiles temporales

---

series_tiempo_ar_api/apps/dump/admin.py
series_tiempo_ar_api/apps/dump/models.py
series_tiempo_ar_api/apps/dump/writer.py

Va de yapa un fix de dumps no borrandose
Closes #418

Features del admin de dumps

---

series_tiempo_ar_api/apps/dump/models.py

Renombro archivos con extension sql a sqlite

---

docs/history.md
mkdocs.yml

Agrego documentación de versiones de la API

---

scripts/integration_test.py
series_tiempo_ar_api/apps/dump/generator/constants.py
series_tiempo_ar_api/apps/dump/generator/metadata.py
series_tiempo_ar_api/apps/dump/generator/sql/generator.py
series_tiempo_ar_api/apps/dump/generator/sql/models.py

Es lo opuesto del campo field.present

Agrego campo 'serie_discontinuada' a los dumps

---

conf/settings/base.py
series_tiempo_ar_api/apps/analytics/models.py
series_tiempo_ar_api/apps/dump/models.py
series_tiempo_ar_api/apps/management/apps.py
series_tiempo_ar_api/apps/management/models.py
series_tiempo_ar_api/apps/metadata/models.py

- Activo i18n y configuro el lenguaje a español de Argentina
- Cambio de nombres verbose de los modelos de la API

Traducción del admin a español

---

conf/settings/base.py
conf/settings/production.py
conf/settings/staging.py
conf/settings/testing.py
requirements/base.txt
series_tiempo_ar_api/apps/analytics/tasks.py
series_tiempo_ar_api/apps/dump/tasks.py
series_tiempo_ar_api/apps/dump/writer.py
series_tiempo_ar_api/apps/management/tasks/indexation.py
series_tiempo_ar_api/apps/management/tasks/integration_test.py
series_tiempo_ar_api/apps/metadata/indexer/metadata_indexer.py
series_tiempo_ar_api/libs/indexing/tasks.py

Setea la configuración y los tasks asincrónicos necesarios para poder configurar la cola de tareas desde la UI de django-datajsonar de nuevo proceso.
Closes #450

Integración con django datajsonar Synchronizers

---

series_tiempo_ar_api/apps/dump/generator/constants.py
series_tiempo_ar_api/apps/dump/generator/metadata.py
series_tiempo_ar_api/apps/dump/generator/sql/generator.py
series_tiempo_ar_api/apps/dump/generator/sql/models.py
series_tiempo_ar_api/apps/dump/generator/xlsx/formats.py
series_tiempo_ar_api/apps/dump/tests/csv_generator_tests.py
series_tiempo_ar_api/apps/dump/tests/sql_generator_tests.py
series_tiempo_ar_api/apps/management/meta_keys.py
series_tiempo_ar_api/utils/utils.py

Closes #415 
Asumiendo que existen siempre los metadatos de consultas para cada serie, las escribo en el dump de metadatos, agregando 4 nuevas columnas.

Metadatos de consultas en dumps

---

series_tiempo_ar_api/apps/metadata/indexer/catalog_meta_indexer.py
series_tiempo_ar_api/apps/metadata/indexer/doc_types.py
series_tiempo_ar_api/apps/metadata/queries/query.py
series_tiempo_ar_api/apps/metadata/tests/indexer_tests.py
series_tiempo_ar_api/apps/metadata/tests/query_tests.py

Ordeno resultados de búsqueda según la cantidad de hits

---

series_tiempo_ar_api/apps/metadata/queries/query_terms.py
series_tiempo_ar_api/apps/metadata/tests/field_term_tests.py
series_tiempo_ar_api/apps/metadata/tests/view_tests.py

Reverts datosgobar/series-tiempo-ar-api#483

Revert "Muestro cantidad de hits en endpoints auxiliares"

---

series_tiempo_ar_api/apps/analytics/elasticsearch/indicators.py
series_tiempo_ar_api/libs/indexing/popularity.py
series_tiempo_ar_api/libs/indexing/scraping.py
series_tiempo_ar_api/libs/indexing/tests/popularity_metadata_tests.py
series_tiempo_ar_api/libs/indexing/tests/scraper_tests.py
series_tiempo_ar_api/utils/csv_reader.py

Paso a utilizar repositories para leer las distribuciones o series requeridas en cada caso particular

Reemplazo ocurrencias de 'indice_tiempo' hardcodeados

---

conf/settings/testing.py
series_tiempo_ar_api/libs/indexing/report/node_admins.py
series_tiempo_ar_api/libs/indexing/report/report_generator.py
series_tiempo_ar_api/libs/indexing/report/report_mail_sender.py
series_tiempo_ar_api/libs/indexing/tests/report_mail_sender_tests.py

Encapsulo y agrego tests sobre el mandado del reporte de indexación.

Refactor email reports

---

series_tiempo_ar_api/libs/indexing/indexer/distribution_indexer.py
series_tiempo_ar_api/libs/indexing/strings.py
series_tiempo_ar_api/libs/indexing/tests/distribution_indexer_tests.py
series_tiempo_ar_api/libs/indexing/tests/samples/series_metadata_no_identifier.csv
series_tiempo_ar_api/libs/indexing/tests/samples/series_metadata_no_identifier.json

Fix a distribuciones sin series indexandose

---

series_tiempo_ar_api/apps/api/query/es_query/es_query.py
series_tiempo_ar_api/apps/api/query/query.py
series_tiempo_ar_api/apps/api/tests/es_query_tests.py
series_tiempo_ar_api/apps/api/tests/query_tests.py

Bugfix: series con aggregations sin collapse no funcionaban

---

series_tiempo_ar_api/apps/analytics/importer.py
series_tiempo_ar_api/apps/analytics/tests/import_tests.py

Closes #550 
- Filtra las queries que vengan con método `OPTIONS`
- Test del comportamiento

550 report options exclude

---

requirements/base.txt
series_tiempo_ar_api/libs/datajsonar_repositories/node_repository.py
series_tiempo_ar_api/libs/indexing/distribution_validator.py
series_tiempo_ar_api/libs/indexing/errors/distribution_validator.py
series_tiempo_ar_api/libs/indexing/tests/distribution_validator_tests.py
series_tiempo_ar_api/libs/indexing/tests/samples/repeated_field_id_and_description.json
series_tiempo_ar_api/libs/indexing/tests/samples/repeated_field_id_and_description_data.csv

Devuelve todos los errores de la distribución en una lista en vez de lanzar excepción al primer error encontrado
Closes #531

Utilizo get_distribution_errors para validar distribuciones

---

docs/spreadsheet-integration.md

Syntax issues on paragraph 95, 105, 112

---

series_tiempo_ar_api/libs/indexing/catalog_reader.py
series_tiempo_ar_api/libs/indexing/tests/reader_tests.py

Paso catalog_format a la lectura de DataJson

---

series_tiempo_ar_api/apps/api/query/es_query/es_query.py
series_tiempo_ar_api/apps/api/query/es_query/series.py
series_tiempo_ar_api/apps/api/query/query.py
series_tiempo_ar_api/apps/api/tests/es_query_tests.py
series_tiempo_ar_api/apps/api/tests/query_tests.py

Closes #616 
Aproveché para meter un par de refactors adicionales

Corrección de agregaciones

---

series_tiempo_ar_api/apps/management/meta_keys.py
series_tiempo_ar_api/libs/indexing/indexer/metadata.py
series_tiempo_ar_api/libs/indexing/tests/metadata_tests.py
series_tiempo_ar_api/libs/utils/significant_figures.py
series_tiempo_ar_api/libs/utils/tests/significant_figures_tests.py

Metadato enriquecido: cifras significativas

---

series_tiempo_ar_api/libs/indexing/indexer/metadata.py
series_tiempo_ar_api/libs/utils/significant_figures.py
series_tiempo_ar_api/libs/utils/tests/significant_figures_tests.py

Closes #628 
- Maneja el caso de una serie compuesta de floats sin parte decimal
- Agrega test del comportamiento

628 point zero floats

---

series_tiempo_ar_api/apps/api/query/es_query/es_query.py
series_tiempo_ar_api/apps/api/query/query.py
series_tiempo_ar_api/apps/api/tests/query_tests.py

Collapse aggregation multiple series

---

series_tiempo_ar_api/libs/indexing/report/report_mail_sender.py
series_tiempo_ar_api/libs/indexing/tests/report_mail_sender_tests.py

Closes #633 
- Agrego el remitente de los mails de reportes en CCO
- Agrego test

Agrego al remitente de los mails de reportes en CCO. 

---

series_tiempo_ar_api/libs/utils/significant_figures.py
series_tiempo_ar_api/libs/utils/tests/significant_figures_tests.py

Aplico heurística para solucionar problemas de respresentación decimal en floats

---

series_tiempo_ar_api/apps/dump/generator/generator.py
series_tiempo_ar_api/apps/dump/tests/csv_generator_tests.py

Closes #641 
El test de integración utiliza los dumps CSV de base. En staging no se generaban bien por la no existencia de ciertos valores del metadato periodicity. En vez de fallar si no existe, se decide propagar el null.

Corrijo generación de dumps CSV cuando no existe periodicity

---

series_tiempo_ar_api/apps/metadata/indexer/metadata_indexer.py
series_tiempo_ar_api/apps/metadata/tests/run_metadata_indexer_tests.py

Se cambia un poco la logica de indexado cuando se envia un único nodo a indexar.
closes #663

Indexado de metadatos de un solo nodo

---

series_tiempo_ar_api/apps/api/models.py
series_tiempo_ar_api/apps/api/query/es_query/es_query.py
series_tiempo_ar_api/apps/api/query/es_query/response_formatter.py
series_tiempo_ar_api/apps/api/query/es_query/series.py
series_tiempo_ar_api/apps/api/query/pipeline.py
series_tiempo_ar_api/apps/api/query/query.py
series_tiempo_ar_api/apps/api/query/series_query.py
series_tiempo_ar_api/apps/api/tests/endpoint_tests/aggregations_tests.py
series_tiempo_ar_api/apps/api/tests/endpoint_tests/collapse_tests.py
series_tiempo_ar_api/apps/api/tests/endpoint_tests/date_filter_tests.py
series_tiempo_ar_api/apps/api/tests/endpoint_tests/endpoint_test_case.py
series_tiempo_ar_api/apps/api/tests/es_query_tests.py
series_tiempo_ar_api/apps/api/tests/helpers.py
series_tiempo_ar_api/apps/api/tests/pipeline_tests/date_filter_tests.py
series_tiempo_ar_api/apps/api/tests/pipeline_tests/delimiter_decimal_tests.py
series_tiempo_ar_api/apps/api/tests/pipeline_tests/last_tests.py
series_tiempo_ar_api/apps/api/tests/pipeline_tests/pagination_tests.py
series_tiempo_ar_api/apps/api/tests/pipeline_tests/sort_tests.py
series_tiempo_ar_api/apps/api/tests/query_tests.py
series_tiempo_ar_api/apps/api/tests/response_tests.py
series_tiempo_ar_api/apps/api/tests/support/generate_data.py
series_tiempo_ar_api/apps/api/tests/support/test_data_values.py

Series endpoint refactor

---

series_tiempo_ar_api/libs/indexing/report/report_generator.py
series_tiempo_ar_api/libs/indexing/tests/report_tests.py
series_tiempo_ar_api/libs/indexing/tests/samples/broken_catalog.json

Closes #667 
También incluye una optimización en los tests de reporte:
- Reemplazo las URLs de descarga (que devolvían 404) por propias a localhost
- Corrijo el mock de DistributionIndexer, no estaba bien aplicado

Agrego id del nodo en el asunto de reportes

---

series_tiempo_ar_api/apps/api/query/es_query/es_query.py
series_tiempo_ar_api/apps/api/tests/endpoint_tests/collapse_tests.py

Fix a colapso automático no aplicándose
